### PR TITLE
76 Added Extension for AdministrativeGender

### LINKED ISSUE #76: Add additional administrative gender codes to Patient
**Real Submitter**
@regelkraut 

**Resource(s)/Profiles incl. Version**
Resource Patient in STU2 of the HL7 AT FHIR Core IG

**Links**
[HL7 AT FHIR Core IG: Patient STU2](https://fhir.hl7.at/r4-core-main/StructureDefinition-at-core-patient.html)

**Priority**
Major

**Is your feature request related to a problem? Please describe.**
The current profile on Patient (nor the FHIR Core spec) does not support the legal requirement in Austria for additional administrative genders.

**Describe the solution you'd like**
The TC Terminology already [balloted the new valueSets](https://collab.hl7.at/pages/viewpage.action?pageId=90537991) that are to be applied. Since administrative gender has an required valueSet binding in the FHIR Core spec. we are not allowed to extend the existing valueSet. But it is possible to put an Extension on it, an approach which was also done by our colleagues from Germany.

**Describe alternatives you've considered**
We checked if we could use another gender related attribute or one of the extension provided by the gender harmony project for this requirement, but applying the extension to administrative gender is the way to go.

**Additional context**
N/a

### PR DESCRIPTION
**Pull request by regelkraut**
The Extension has a required binding to the corresponding value set for addtional adminstrative gender codes.

Closes #76

### CODE REVIEW

**Review by oliver-krauss — COMMENTED** [review]
I wasnt in the call but should this not be aligned with the GenderHarmony project of HL7 Internatinoal? 
https://build.fhir.org/ig/HL7/fhir-gender-harmony/branches/main/fhirgenderharmony.html

E.g. http://hl7.org/fhir/extensions/StructureDefinition-individual-genderIdentity.html but with the TC Terminology defined ValueSet (since it is preferred in the extension anyways we can do that)

**Comment by regelkraut** [comment]
> I wasnt in the call but should this not be aligned with the GenderHarmony project of HL7 Internatinoal? https://build.fhir.org/ig/HL7/fhir-gender-harmony/branches/main/fhirgenderharmony.html
> 
> E.g. http://hl7.org/fhir/extensions/StructureDefinition-individual-genderIdentity.html but with the TC Terminology defined ValueSet (since it is preferred in the extension anyways we can do that)

Good input. We already talked about this topic during one the TC FHIR calls. The content of the gender harmony project does not affect the administrative gender itself, which is the goal of the legal requirement in Austria. The gender harmony project has its focus on other gender aspects like identity, pronouns etc.
This enhancement of the administrative gender does not interfere with the possibilities of the GHP, both can be applied independently.

**Comment by oliver-krauss** [comment]
> > I wasnt in the call but should this not be aligned with the GenderHarmony project of HL7 Internatinoal? https://build.fhir.org/ig/HL7/fhir-gender-harmony/branches/main/fhirgenderharmony.html
> > E.g. http://hl7.org/fhir/extensions/StructureDefinition-individual-genderIdentity.html but with the TC Terminology defined ValueSet (since it is preferred in the extension anyways we can do that)
> 
> Good input. We already talked about this topic during one the TC FHIR calls. The content of the gender harmony project does not affect the administrative gender itself, which is the goal of the legal requirement in Austria. The gender harmony project has its focus on other gender aspects like identity, pronouns etc. This enhancement of the administrative gender does not interfere with the possibilities of the GHP, both can be applied independently.

ok in this case I will approve my Review thanks for clarification

**Review by oliver-krauss — APPROVED** [review]

**Review by gabriel0316 — COMMENTED** [review]
Currently, we have the invariant `at-ext-gender-1` within the extension. I think, this invariant checks that the corresponding `gender` of the resource is `other`. 

I now have two questions:
- If `Patient.gender` and `Patient.contact.gender` are present, which of them is checked by the invariant? 
- Do we need another invariant on the Patient requiring the use of the extension in case any gender is `other`?

**Comment by regelkraut** [comment]
> Currently, we have the invariant `at-ext-gender-1` within the extension. I think, this invariant checks that the corresponding `gender` of the resource is `other`.
> 
> I now have two questions:
> 
> * If `Patient.gender` and `Patient.contact.gender` are present, which of them is checked by the invariant?
> * Do we need another invariant on the Patient requiring the use of the extension in case any gender is `other`?

The current invariant just checks `Patient.gender`.
For `Patient.contact.gender` we could create an additional invariant (which should be fine, because the other Resources that are able to use this extension don't have a *.contact element, hence the new invariant would just be applied for `Patient.contact`)

**Comment by gabriel0316** [comment]
> > Currently, we have the invariant `at-ext-gender-1` within the extension. I think, this invariant checks that the corresponding `gender` of the resource is `other`.
> > I now have two questions:
> > 
> > * If `Patient.gender` and `Patient.contact.gender` are present, which of them is checked by the invariant?
> > * Do we need another invariant on the Patient requiring the use of the extension in case any gender is `other`?
> 
> The current invariant just checks `Patient.gender`. For `Patient.contact.gender` we could create an additional invariant (which should be fine, because the other Resources that are able to use this extension don't have a *.contact element, hence the new invariant would just be applied for `Patient.contact`)

I see - What about the invariant in the Patient resource?

**Comment by regelkraut** [comment]
> > > Currently, we have the invariant `at-ext-gender-1` within the extension. I think, this invariant checks that the corresponding `gender` of the resource is `other`.
> > > I now have two questions:
> > > 
> > > * If `Patient.gender` and `Patient.contact.gender` are present, which of them is checked by the invariant?
> > > * Do we need another invariant on the Patient requiring the use of the extension in case any gender is `other`?
> > 
> > 
> > The current invariant just checks `Patient.gender`. For `Patient.contact.gender` we could create an additional invariant (which should be fine, because the other Resources that are able to use this extension don't have a *.contact element, hence the new invariant would just be applied for `Patient.contact`)
> 
> I see - What about the invariant in the Patient resource?

Result of the discussion during the [TC FHIR Call on January 25th 2024](https://collab.hl7.at/x/jQAWBg):
* An additional invariant to the Extension will be added for `Patient.contact.gender`
* No invariant will be put on `Patient` etc. to enforce the use of the Extension, since the use of it should just be an option

**Review by gabriel0316 — APPROVED** [review]

**Pull request merged**
