### PR TITLE
#14 add new examples for austrianPatient

### LINKED ISSUE #14: Example for AustrianPatient - More examples for the Austrian Patient profile
**Real Submitter**
@regelkraut 

**Resource(s)/Profiles incl. Version**
Austrian Patient, STU1

**Links**
https://hl7austria.github.io/r4-core-ballot_2021_01/StructureDefinition-austrian-patient-examples.html

**Priority**
Minor

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Introduce more examples for the Austrian Patient profile to increase the understanding of the usage.

**Describe alternatives you've considered**
None.

**Additional context**
None.

### LINKED ISSUE #17: Examples for profiles and extensions
**Real Submitter**
FH Johanneum, Carina Seerainer

**Resource(s)/Profiles incl. Version**
HL7 AT FHIR Core IG STU1

**Links**
https://hl7austria.github.io/r4-core-ballot_2021_01/artifacts.html

**Priority**
Major

**Is your feature request related to a problem? Please describe.**
There is just an example for the Austrian Patient but nothing for the other profiles and extensions.

**Describe the solution you'd like**
Introduce an "example tab" also for the other profiles and extensions.

**Describe alternatives you've considered**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by Nik-xT**
Creating pull request to activate github actions and test the changes.

Edit by oliver: 
Closes #14 
Closes #17

### CODE REVIEW

**Review by regelkraut — CHANGES_REQUESTED** [review]
Thanks for the additional examples, however the qa report which is generated by the IG publisher automatically complains about a couple of things, see:
https://hl7austria.github.io/r4-core-master/qa.html

Please address them accordingly. 
Concerning the error about the special characters  for the display name of the social security number - it works for me to convert the fsh-files to UTF-8 before running sushi. Maybe this helps.

**Comment by dimitrov-alex** [comment]
Hi @regelkraut was just about to update the examples, but noticed that the attached qa report (https://hl7austria.github.io/r4-core-master/qa.html) is from Oct 19 13:53:54 and the errors are not included in it any more. Could you generate the report again, so the UTF errors etc. are visiable again? thanks!

**Comment by oliver-krauss** [comment]
> Hi @regelkraut was just about to update the examples, but noticed that the attached qa report (https://hl7austria.github.io/r4-core-master/qa.html) is from Oct 19 13:53:54 and the errors are not included in it any more. Could you generate the report again, so the UTF errors etc. are visiable again? thanks!

Hi @dimitrov-alex Unfortunately this is a known bug right now that I haven't gotten around to fixing yet (https://github.com/HL7Austria/HL7-AT-FHIR-Core-R4/issues/25). If you commit anything on this branch you will get the QA report for the current branch again (e.g. just edit the readme file with a new line etc.)

**Comment by dimitrov-alex** [comment]
QA report got updated, thanks for the help! 

> 
> 
> > Hi @regelkraut was just about to update the examples, but noticed that the attached qa report (https://hl7austria.github.io/r4-core-master/qa.html) is from Oct 19 13:53:54 and the errors are not included in it any more. Could you generate the report again, so the UTF errors etc. are visiable again? thanks!
> 
> Hi @dimitrov-alex Unfortunately this is a known bug right now that I haven't gotten around to fixing yet (#25). If you commit anything on this branch you will get the QA report for the current branch again (e.g. just edit the readme file with a new line etc.)

QA report got updated, thanks for the help!

**Comment by dimitrov-alex** [comment]
Mentioned errors were fixed with the last commits.
The following error is still appearing, due to no available organization examples yet:
`Unable to resolve resource 'Organization/POZ-10'`

**Comment by oliver-krauss** [comment]
> Mentioned errors (from the QA report) were fixed with the last commits. The following error is still appearing (in Patient-HL7ATCorePatientExample04-Full), due to no available organization examples yet: `Unable to resolve resource 'Organization/POZ-10'`

As discussed in Call on 18 Nov - @dimitrov-alex will add an Organization example (copy paste from HL7 Intl.)

**Comment by dimitrov-alex** [comment]
Added a fsh file based on the example from the HL7 FHIR specification (http://hl7.org/fhir/organization-example-f001-burgers.html). 
Mentioned errors are not accuring any more

**Review by oliver-krauss — CHANGES_REQUESTED** [review]
@dimitrov-alex I think you wanted to add me as reviewer. I concur, the exceptions are gone. one final question before I approve -> https://fhir.hl7.at/r4-core-ballot_2021_01/StructureDefinition-austrian-patient-examples.html You uploaded multiple examples. Why is only one shown in the index? https://fhir.hl7.at/r4-core-ballot_2021_01/artifacts.html#example-example-instances

**Comment by dimitrov-alex** [comment]
> @dimitrov-alex I think you wanted to add me as reviewer. I concur, the exceptions are gone. one final question before I approve -> https://fhir.hl7.at/r4-core-ballot_2021_01/StructureDefinition-austrian-patient-examples.html You uploaded multiple examples. Why is only one shown in the index? https://fhir.hl7.at/r4-core-ballot_2021_01/artifacts.html#example-example-instances

@oliver-krauss Yes, ment to set you as a reviewer. 

The fsh files were only pushed to the following branch:
https://github.com/HL7Austria/HL7-AT-FHIR-Core-R4/tree/14-more-examples
Should I push them to the main branch?

**Comment by oliver-krauss** [comment]
> > @dimitrov-alex I think you wanted to add me as reviewer. I concur, the exceptions are gone. one final question before I approve -> https://fhir.hl7.at/r4-core-ballot_2021_01/StructureDefinition-austrian-patient-examples.html You uploaded multiple examples. Why is only one shown in the index? https://fhir.hl7.at/r4-core-ballot_2021_01/artifacts.html#example-example-instances
> 
> @oliver-krauss Yes, ment to set you as a reviewer.
> 
> It migth the issue, that the fsh files were only pushed to the following branch: https://github.com/HL7Austria/HL7-AT-FHIR-Core-R4/tree/14-more-examples Should I push them to the main branch?

Not the Case I think.  

https://fhir.hl7.at/r4-core-master/index.html shows the last branch built, which is this one. So the files are there they just aren't linked in the overview for some reason?

**Comment by dimitrov-alex** [comment]
Under https://fhir.hl7.at/r4-core-master/artifacts.html they seem to be listed for me:
grafik

**Comment by oliver-krauss** [comment]
> Under https://fhir.hl7.at/r4-core-master/artifacts.html they seem to be listed for me: grafik

Yepp me too now. Maybe my cache wasn't cleared.

**Review by oliver-krauss — APPROVED** [review]

**Review by dimitrov-alex — APPROVED** [review]

**Comment by oliver-krauss** [comment]
Since we got several approvals I think we are good here. WIll merge

**Pull request merged**
