### PR TITLE
#13 adding OID to ValueSets and CodeSystems

### PR DESCRIPTION
**Pull request by Nik-xT**
Creating pull request to activate github actions and test the changes.

Edit by Oliver: 
Closes: #13

### CODE REVIEW

**Comment by Nik-xT** [comment]
Identifier has been added, see https://hl7austria.github.io/r4-core-master/ValueSet-at-elga-vs-religion.xml.html .
However, there is no visualization of it in the narrative content: https://hl7austria.github.io/r4-core-master/ValueSet-at-elga-vs-religion.html . 
other terminologies will follow now.

**Review by oliver-krauss — APPROVED** [review]
All 4 VS and CS now have use and code system. The system should be correct as well.

**Review by dimitrov-alex — APPROVED** [review]

**Comment by Nik-xT** [comment]
Not having any rights to push to main from local. @oliver-krauss : please solve the conflicts locally (longer description is the right one) and merge the changes into master.

**Comment by oliver-krauss** [comment]
> Not having any rights to push to main from local. @oliver-krauss : please solve the conflicts locally (longer description is the right one) and merge the changes into master.

I'd ask you to please do the rebase locally and push to this branch again (force push).

**Comment by oliver-krauss** [comment]
HOW? 
Merging is disabled and you got no admin rights. We got a security leak in the settings it seems.

**Comment by oliver-krauss** [comment]
@Nik-xT  please _**REBASE**_ locally. No merges.

**Comment by Nik-xT** [comment]
I dont understand the problem. The merge request had enough approvals and the local merge is recommended when the automatic merge in github is not working (even Github was suggesting this). Imho, this is not a security leak, its a feature. Do i miss something?

**Comment by oliver-krauss** [comment]
It should not have been possible for you to "merge" :D the settings are set to only allow "rebase" -> https://www.atlassian.com/git/tutorials/merging-vs-rebasing 

This is the only thing you are missing. "git rebase". I'm gonna send the doodles out for next week again, so we can do a session together next week maybe.

**Pull request merged**
